//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prefix
    {
        public int PrefixesId { get; set; }
        public Nullable<int> OperatorsId { get; set; }
        public string Prefix1 { get; set; }
    
        public virtual Operator Operator { get; set; }
    }
}
